<?php

/**
 * Created by PhpStorm.
 * User: Vlad
 * Date: 11.02.2016
 * Time: 23:38
 */
namespace app\widgets;

use app\widgets;
use app\widgets\assets\AssetImageUpload;
use Yii;
use yii\helpers\Html;

class ImageUpload extends \yii\widgets\InputWidget
{
    public function init()
    {
        parent::init();
        $view = $this->getView();
        $asset = Yii::$container->get(AssetImageUpload::className());
        $asset = $asset::register($view);
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $attr = $this->attribute;
        $img = $this->model->$attr;
        $formName = $this->model->formName();
        $inputName = $formName . "[" . $attr . "]";
        $response = "<div class='img-upl'>";
        $response .= "<img src='" . $img . "' class='upload-image'/>" . "\n";
        $response .= "<input type='hidden' name='" . $inputName . "' value='" . $img . "'> ";
        $response .= "<div class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">
        <div class=\"modal-dialog\">
            <div class=\"modal-content\">
                <div class=\"modal-header\">
                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>
                    <h4 class=\"modal-title\">Загрузка изображения</h4>
                </div>
                <div class=\"modal-body\">
                </div>
                <div class=\"modal-footer\">
                <label for='image-upload' class=\"btn btn-primary\">Загрузить</label>
                <input type='file' id='image-upload' name='UploadForm[imageFile]'>
                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->";
        $response .= "</div>";
//        return Html::activeTextarea($this->model, $this->attribute);
        return $response;
    }
}