<?php
/**
 * Created by PhpStorm.
 * User: Vlad
 * Date: 29.02.2016
 * Time: 17:06
 */

namespace app\widgets;



use app\models\LoginForm;
use yii\bootstrap\Widget;

class LoginWidget extends Widget
{
    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new LoginForm();
    }

    public function run()
    {
        return $this->render('_login', [
            'model' => $this->model,
        ]);
    }
}