<?php
/**
 * Created by PhpStorm.
 * User: Vlad
 * Date: 29.02.2016
 * Time: 17:06
 */

namespace app\widgets\banners;



use app\models\Banners;
use app\models\LoginForm;
use yii\bootstrap\Widget;

class BannersWidget extends Widget
{
    public $banners;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->banners = Banners::getBanners()->limit(3)->all();
    }

    public function run()
    {
        return $this->render('_banners', [
            'model' => $this->banners,
        ]);
    }
}